config/routes.rb
Rails.application.routes.draw do

  root 'movies#index'

  get 'movies/up' => 'movies#up', as: :up
  get 'movies/upAttempt' => 'movies#upAttempt', as: :upAttempt
  
  get 'movies/deleteopt' => 'movies#deleteopt', as: :deleteopt
  get 'movies/delete' => 'movies#delete', as: :delete
  get 'movies/del' => 'movies#del', as: :del
  get 'movies/delopt' => 'movies#delopt', as: :delopt

  resources :movies
  

end

app/models/movie.rb
class Movie < ActiveRecord::Base
 # validates :title, presence: true
    @all_ratings = ["G", "PG", "PG-13", "R", "NC-17"]
#  validates :rating, presence: true
#  validates :release_date, presence: true
    def self.all_ratings
        @all_ratings
    end

    def all_ratings
        self.class.all_ratings
    end
    
    def ratings
        all_ratings
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def movie_params
    params.require(:movie).permit(:title, :rating, :description, :release_date)
  end

  def movie_params2
    params.require(:movie).permit(:title, :rating)
  end

  def show
    id = params[:id] # retrieve movie ID from URI route
    @movie = Movie.find(id) # look up movie by unique ID
    # will render app/views/movies/show.<extension> by default
  end

  def index
    @movies = Movie.order(params[:sort])
    @hilite = "hilite"
    @all_ratings = ["G", "PG", "PG-13", "R", "NC-17"]
     if !(params[:ratings].nil?)
       @movies = @movies.find_all{ |m| params[:ratings].has_key?(m.rating) }
     end
  end

  def new
    # default: render 'new' template
  end

  def create
    @movie = Movie.create!(movie_params)
    flash[:notice] = "#{@movie.title} was successfully created."
    redirect_to movies_path
  end

  def edit
    @movie = Movie.find params[:id]
  end
  
  def up
   
  end
  
  def upAttempt
    @movie = Movie.find_by_title(params[:movie2update][:title])
    #@movie = Movie.find params[:id]
    if @movie
      @movie.update_attributes!(movie_params)
      flash[:notice] = "#{@movie.title} was successfully updated."
      redirect_to movie_path(@movie)
    elsif params[:movie2update][:title].blank?  || params[:movie][:title].blank?
      flash[:notice] = "ERROR: One or more field empty. Fill in all fields"
      render 'up'
    else
      flash[:notice] = "ERROR: #{params[:movie2update][:title]} wasn't found in database."
      render 'up'
    end
  end
  
  def delete
   
  end
  
  def del
    @movie = Movie.find_by_title(params[:movie2delete][:title])
    #@movie = Movie.find params[:id]
    if @movie
      @movie.destroy
      flash[:notice] = "Movie '#{@movie.title}' deleted."
      redirect_to movies_path
    elsif params[:movie2delete][:title].blank?
      flash[:notice] = "ERROR: One or more field empty. Fill in all fields"
      render 'delete'
    else
      flash[:notice] = "ERROR: #{params[:movie2delete][:title]} wasn't found in database."
      render 'delete'
    end
  end
 
  def deleteopt 
  
  end
 
  def delopt
    @movie = Movie.find_by_rating(params[:movie2delete][:rating])
    #@movie = Movie.find params[:id]
    
    if @movie
      while @movie do
        @movie.destroy
        @movie = Movie.find_by_rating(params[:movie2delete][:rating])
        if !@movie
          flash[:notice] = "All #{params[:movie2delete][:rating]} movies deleted."
          redirect_to movies_path
          break
        end
      end
    elsif params[:movie2delete][:rating].blank?
      flash[:notice] = "ERROR: One or more field empty. Fill in all fields"
      render 'deleteopt'
    else
      flash[:notice] = "ERROR: There was no #{params[:movie2delete][:rating]} movies in database."
      render 'deleteopt'
    end
  end

  def update
    @movie = Movie.find params[:id]
    @movie.update_attributes!(movie_params)
    flash[:notice] = "#{@movie.title} was successfully updated."
    redirect_to movie_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    flash[:notice] = "Movie '#{@movie.title}' deleted."
    redirect_to movies_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  # Checks if a number is odd:
  def oddness(count)
    count.odd? ?  "odd" :  "even"
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Rotten Potatoes!
    = stylesheet_link_tag 'application', 'media' => 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %h1.title Rotten Potatoes!
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]

      = yield

app/views/movies/delete.html.haml
%h1 Delete Movie by Title

= form_tag del_path, :method => :get do
    
  = label :movie, :title, 'Delete Movie by Title'
  = text_field :movie2delete, 'title'

  = submit_tag 'Delete Movie'

= link_to 'Back to movie list', movies_path

app/views/movies/deleteopt.html.haml
%h1 Delete Movie by Rating

= form_tag delopt_path, :method => :get do
  
  = label :movie, :title, 'Delete Movie by Rating'
  = select :movie2delete, :rating, ['G','PG','PG-13','R','NC-17']

  = submit_tag 'Delete Movie'
  
= link_to 'Back to movie list', movies_path

app/views/movies/edit.html.haml
-# edit.html.haml using partial

%h1 Edit Existing Movie

= form_tag movie_path(@movie), :method => :put do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Update Movie Info'

app/views/movies/index.html.haml
-#  This file is app/views/movies/index.html.haml
%h1 All Movies

= form_tag movies_path, :method => :get do
  Include:
  - @all_ratings.each do |rating|
    = rating
    = check_box_tag "ratings[#{rating}]", "1",(@ratings ? @ratings.include?(rating) : true)
  = submit_tag 'Refresh'


%table#movies
  %thead
    %tr
      //%th Movie Title
      %th= link_to "Movie Title", :sort => "title"
      %th Rating
      %th= link_to "Release Data", :sort => "release_date"
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title 
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)


%br= link_to 'Delete movie by Title', delete_path
%br= link_to 'Delete movie by Rating', deleteopt_path
%br= link_to 'Add new movie', new_movie_path
%br= link_to 'Update a movie', up_path

app/views/movies/new.html.haml
%h1 Create New Movie

= form_tag movies_path do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Save Changes'

app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml

%h2 Details about #{@movie.title}

%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Released on:
    = @movie.release_date.strftime("%B %d, %Y")

%h3 Description:

%p#description= @movie.description

= link_to 'Edit', edit_movie_path(@movie)
= button_to 'Delete', movie_path(@movie), :method => :delete, :confirm => 'Are you sure?'
= link_to 'Back to movie list', movies_path

app/views/movies/up.html.haml
%h1 Update Movie

= form_tag upAttempt_path, :method => :get do

  = label :movie, :title, 'Old Title'
  = text_field :movie2update, 'title'

  = label :movie, :title, 'New Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Update Movie'
  
= link_to 'Back to movie list', movies_path